"""Turn assets/portrait-source.png into the brightness grid used by the hero's binary portrait.

Run: pip install "rembg[cpu]" pillow numpy && python scripts/build-portrait.py
Writes content/portrait.ts. Cell value 0 = background, 1..255 = brightness inside the person.
"""

import base64
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter, ImageOps
from rembg import new_session, remove

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "portrait-source.png"
OUT = ROOT / "content" / "portrait.ts"
COLS = 120

img = Image.open(SRC).convert("RGB")
cut = remove(img, session=new_session("u2net_human_seg"))
rows = round(COLS * img.height / img.width)

alpha = np.asarray(cut.getchannel("A").resize((COLS, rows), Image.LANCZOS), dtype=np.float32) / 255
gray = ImageOps.grayscale(img).resize((COLS, rows), Image.LANCZOS)
g = np.asarray(gray, dtype=np.float32) / 255
# Local contrast: subtract a blurred copy so facial features read at small cell sizes.
blur = np.asarray(gray.filter(ImageFilter.GaussianBlur(COLS / 24)), dtype=np.float32) / 255
local = np.clip(0.5 + 1.6 * (g - blur), 0, 1)
lum = 0.55 * local + 0.45 * g
inside = alpha > 0.5
lo, hi = np.percentile(lum[inside], [2, 98])
lum = np.clip((lum - lo) / (hi - lo), 0, 1) ** 0.9

value = np.where(alpha > 0.5, 0.18 + 0.82 * lum, 0)
grid = np.clip(np.round(value * 255), 0, 255).astype(np.uint8)
grid[(alpha > 0.5) & (grid == 0)] = 1

b64 = base64.b64encode(grid.tobytes()).decode()
OUT.write_text(
    "// Generated by scripts/build-portrait.py. Do not edit by hand.\n"
    f"export const portrait = {{ cols: {COLS}, rows: {rows}, data: \"{b64}\" }};\n"
)
print(f"wrote {OUT.relative_to(ROOT)}: {COLS}x{rows}, {int((grid > 0).sum())} cells")
